include ../Make.defs
include ../Make.rules

OBJS=exit.o		\
	exec.o 		\
	open.o 		\
	read.o 		\
	close.o 	\
	write.o		\
	yield.o 	\
	getdents.o	\
	modules.o	\
	stat.o		\
	spawn.o		\
	waitpid.o	\
	devs.o		\
	getpid.o	\
	msg.o

all: $(OBJS)
