include ../Make.defs
include ../Make.rules
OBJS=startup.o	\
	 init.o		\
	 console.o	\
	 debug.o	\
	 pci.o		\
	 io.o		\
	 misc.o		\
	 pit.o		\
	 pic.o		\
	 task.o		\
	 task_asm.o \
	 isr.o		\
	 paging.o	\
	 minfo.o	\
	 device.o	\
	 bda.o
	 

all: $(OBJS)
