include ../Make.defs
include ../Make.rules
OBJS=startup.o	\
	 init.o		\
	 debug.o	\
	 misc.o		\
	 isr.o		\
	 isr_asm.o	\
	 paging.o	\
	 device.o	\
	 task.o
	 
#	 task.o		\
#	 task_asm.o \

all: $(OBJS)
