include ../Make.defs
OBJS=stdlib.o 	\
	 syscall.o 	\
	 sched.o	\
	 file.o		\
	 fcntl.o	\
	 stdlib.o	\
	 printf.o	\
	 string.o	\
	 errno.o	\
	 modules.o	\
	 spawn.o	\
	 dirent.o

all: $(OBJS)

include ../../Make.rules
